### ISSUE TITLE
Error while proxying request

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s-ts#17]
When i'm taking images on krystal bull this morning and trying to create an announcement, i'm seeing these errors in my logs. This is on b6f9101f15fbbf99d32905e62d1732e3f09f210c

```
npm run start
oracle-server-ui-proxy@0.0.2 start
npx ts-node server.ts

2021-09-24T12:49:38.570Z Starting oracle-server-ui-proxy
proxyRoot: /proxy oracleServerEndpoint: http://localhost:9998/ oracleExplorerHost: test.oracle.suredbits.com
[HPM] Proxy created: /  -> undefined
[HPM] Proxy rewrite rule created: "^/oracleexplorer" ~> ""
[HPM] Proxy created: /  -> https://blockstream.info/api
[HPM] Proxy rewrite rule created: "^/blockstream" ~> ""
[HPM] Proxy created: /  -> http://localhost:9998/
[HPM] Proxy rewrite rule created: "^/api/v0" ~> ""
2021-09-24T12:49:38.575Z starting HTTP server
2021-09-24T12:49:38.579Z Web Server started on port: 3001 ⚡
oracleExplorerProxyRoot onError
2021-09-24T12:59:28.801Z onError Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.socketCloseListener (_http_client.js:443:25)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7) {
  code: 'ECONNRESET'
} 200 undefined
[HPM] Error occurred while proxying request localhost:3001/announcements/bb038c8f4fca7a9bac6880a05c7a03949f6f0e9e53efd074a4ec7923a6059b42 to https://test.oracle.suredbits.com/v1 [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
oracleExplorerProxyRoot onError
2021-09-24T12:59:28.818Z onError Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.socketCloseListener (_http_client.js:443:25)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7) {
  code: 'ECONNRESET'
} 200 undefined
[HPM] Error occurred while proxying request localhost:3001/announcements/9bdf90c46d62d92d0f0081414d48d8ef4ae571e215ed646bc9f7d701d988d993 to https://test.oracle.suredbits.com/v1 [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
oracleExplorerProxyRoot onError
2021-09-24T12:59:28.820Z onError Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.socketCloseListener (_http_client.js:443:25)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7) {
  code: 'ECONNRESET'
} 200 undefined
[HPM] Error occurred while proxying request localhost:3001/announcements/c59009379119c425b9db31507662c1bfd530a03b4f0455c45aaf0b3aa4b1e54a to https://test.oracle.suredbits.com/v1 [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
oracleExplorerProxyRoot onError
2021-09-24T12:59:28.820Z onError Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.socketCloseListener (_http_client.js:443:25)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7) {
  code: 'ECONNRESET'
} 200 undefined
[HPM] Error occurred while proxying request localhost:3001/announcements/57505dcdfe8746d9adf3454df538244a425f302c07642d9dc4a4f635fbf08d30 to https://test.oracle.suredbits.com/v1 [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
oracleExplorerProxyRoot onError
2021-09-24T12:59:28.821Z onError Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.socketCloseListener (_http_client.js:443:25)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7) {
  code: 'ECONNRESET'
} 200 undefined
[HPM] Error occurred while proxying request localhost:3001/announcements/315f0027a688d9040d3398f678b1cdaf84372a3486b197de3f13196288e08a12 to https://test.oracle.suredbits.com/v1 [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
oracleExplorerProxyRoot onError
2021-09-24T12:59:28.822Z onError Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.socketCloseListener (_http_client.js:443:25)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7) {
  code: 'ECONNRESET'
} 200 undefined
[HPM] Error occurred while proxying request localhost:3001/announcements/f256fd26ac56e6dccf8ab4a71bb397530aadd1ba7b1e3e4b7c08a2f0f76f9e38 to https://test.oracle.suredbits.com/v1 [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by user411** [comment]
I have not seen traces like these yet, but this is why the logging is there. Will keep an eye out for hints on this one.

**Comment by user411** [comment]
When you got the error with proxying requests, were the 6 items in that trace all the items in your event list, or did you notice if they were special in some way?

**Comment by user411** [comment]
I think #22 ultimately solves this issue by bubbling the error up to the UI.
